### ISSUE TITLE
app does not work

### ISSUE THREAD

**Issue by andkom** [pavelfomin/gphoto-manager#7]
```
# sudo java -jar gphoto-manager-0.1.4.jar --albums -token=12345
Invalid options: [--albums, -token=12345]
```

**Comment by pavelfomin** [comment]
Please use the correct syntax:
```
java -jar gphoto-manager-<version>.jar --items-no-album -Dtoken=<access token>
```
Also keep in mind that you need to obtain a proper oauth2 access token. See https://github.com/pavelfomin/gphoto-manager#readme for more details.

**Comment by andkom** [comment]
same error

```
Invalid options: [--items-no-album, -Dtoken=xxxxxxxxxxxxxxxxx]
```

**Comment by pavelfomin** [comment]
Sorry, the `-D` options, including the `-Dtoken=xxx` must be specified before `-jar gphoto-manager-0.1.4.jar`:
```
java -Dtoken=xxx -jar gphoto-manager-0.1.4.jar --albums
```
Docs updated in [0.1.5](https://github.com/pavelfomin/gphoto-manager/releases/tag/0.1.5).
Thank you for pointing this out.
